### ISSUE TITLE
Urgent bug fix ! 

### ISSUE THREAD

**Issue by SaschaAlex** [CmD0/420-4F5#1]
![image](https://user-images.githubusercontent.com/36684458/150883831-a95a990c-7dd9-4ec4-88fb-a47f7ac99b28.png)

**Comment by Fube** [comment]
+1

**Comment by Sersium** [comment]
+1

**Comment by Sersium** [comment]
> ![image](https://user-images.githubusercontent.com/36684458/150883831-a95a990c-7dd9-4ec4-88fb-a47f7ac99b28.png)

same bug tbh

**Comment by Misterjo** [comment]
![image](https://user-images.githubusercontent.com/20408906/151067205-02ffc9ee-00ce-4166-8778-ea50bebbcca8.png)

**Comment by CmD0** [comment]
Thanks for the feedback guys, unfortunately, that's not a valid argument. Please see to this video for the explanation of my reasoning.

https://www.youtube.com/watch?v=dQw4w9WgXcQ
